print ('Будьте внимательны при вводе данных\n ошибка приводит к краху')
myNumber = int(input('введите не дробное число'))
myfloat = float(input('введите дробь'))
mytext = input('Введите текст')
print ('Ваше число -',myNumber,'\nВаша дробь -',myfloat,'\nВаш текст -',mytext)
print ('Вы ввели все правильно!')
